spring:
  application:
    name: Social Impact Tracker

  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/social_impact_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: false
    open-in-view: false

  # JSON 직렬화 설정
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd'T'HH:mm:ss

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# OpenDart API 설정
opendart:
  base-url: https://opendart.fss.or.kr
  api-key: ${DART_API_KEY}
  http:
    connect-timeout-ms: 10000
    read-timeout-ms: 30000
    retry:
      max-attempts: 3
      backoff-ms: 1000

# 데이터 수집 설정
ingest:
  on-startup: false # 시작 시 자동 수집 비활성화 (이미 PowerShell로 저장됨)
  parallelism: 2
  donation:
    on-startup: false  # DART 데이터는 이미 저장되어 있음
    from-year: 2021
    to-year: 2024
    consolidated: true


# 로깅 설정 (콘솔에만 출력, 파일 생성 안 함)
logging:
  level:
    com.socialimpact.tracker: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 스케줄러 설정
spring.task.scheduling.pool.size: 5

# CORS 설정
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  max-age: 3600