server:
  port: 8080

spring:
  task:
    scheduling:
      enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sit?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    hikari:
      connection-timeout: 5000
      minimum-idle: 1
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul

logging:
  level:
    com.impacttracker.backend.ingest: DEBUG  # ← INFO → DEBUG
    com.impacttracker.backend.ingest.dart.DartApiClient: DEBUG
    com.impacttracker.backend.ingest.DartIngestService: DEBUG

impacttracker:
  crawler:
    enabled: true
    user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    timeout-ms: 10000
    delay-between-requests-ms: 2000
    max-retries: 3
    max-concurrent-requests: 5

    targets:
      - name: "DART"
        base-url: "https://dart.fss.or.kr"
        enabled: true
        timeout-ms: 15000
        selector: "table.table-list"

      - name: "ESG"
        base-url: "https://esg.krx.co.kr"
        enabled: false
        timeout-ms: 10000

      - name: "NEWS"
        base-url: "https://search.naver.com"
        enabled: true
        timeout-ms: 8000

    rate-limiting:
      enabled: true
      requests-per-minute: 30
      requests-per-hour: 1000

    proxy:
      enabled: false
      # host: "proxy.example.com"
      # port: 8080
      # username: ""
      # password: ""

opendart:
  base-url: "https://opendart.fss.or.kr"
  api-key: 3dde5cf4bc869c78a13742e04fb27b08fed33530